version: "3.3"

services:
  nginx:
    build: ./nginx
    depends_on:
      - absolute
    ports:
      - "80:80"
      - "443:443"
    networks:
      - absnet
  absolute:
    image: pluto/absolute
    ports:
      - "8080:8080"
    networks:
      - absnet
networks:
  absnet:
