version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: pluto
      POSTGRES_USER: pluto
      POSTGRES_PASSWORD: pluto
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    ports:
      - 9200:9200


