version: '3'
services:
  app1:
    image: scinapse-api
    ports:
      - 8080:8080
      - 5432:5432
      - 9200:9200

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: pluto
      POSTGRES_USER: pluto
      POSTGRES_PASSWORD: pluto
    network_mode: service:app1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.0
    network_mode: service:app1


