INSERT INTO AUTHORITY (ID, NAME, CREATED_AT, UPDATED_AT) VALUES (1, 'ROLE_ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO AUTHORITY (ID, NAME, CREATED_AT, UPDATED_AT) VALUES (2, 'ROLE_USER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO AUTHORITY (ID, NAME, CREATED_AT, UPDATED_AT) VALUES (3, 'ROLE_UNVERIFIED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);